name: dart_application_1
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  intl: ^0.19.0  # For date/time formatting
  
dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
