name: parking_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.0
  go_router: ^14.7.2
  cupertino_icons: ^1.0.8
  shared: 
    path: '../shared'
  firebase_repositories: 
    path: '../firebase_repositories'
  intl: ^0.20.1
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  mocktail: ^1.0.4
  bloc_test: ^9.1.7
  equatable: ^2.0.7
  hydrated_bloc: ^9.1.5
  path_provider: ^2.1.5
  replay_bloc: ^0.2.7
  test: ^1.25.7
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  datetime_picker_formfield: ^2.0.1
  cloud_firestore: ^5.6.3
  uuid: ^4.5.1
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  flutter_timezone: ^4.1.0

  notification_utils: # Add this line!
    # If the package is local:
    path: '../notification_utils' 
    # If the package is on pub.dev (replace with the correct version):
    # ^1.0.0  # Or the appropriate version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true