name: admin_app # Add this field with your project name
description: "A new Flutter project."

publish_to: 'none' # Prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  # sdk: ^3.6.0
  sdk: ">=2.17.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared: 
    path: '../shared'
  firebase_repositories: 
    path: '../firebase_repositories'
  go_router: ^14.6.2
  google_fonts: ^6.2.1
  provider: ^6.1.2
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  bloc_test: ^9.1.7
  equatable: ^2.0.7
  hydrated_bloc: ^9.1.5
  path_provider: ^2.1.5
  replay_bloc: ^0.2.7
  intl: ^0.20.1
  test: ^1.25.7
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
