name: cli
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: ^3.5.3

dependencies:
  http: ^1.2.2
  cli_shared:
    path: '../cli_shared'
  # Optional, add if you need ObjectBox on the client side
  objectbox: ^4.0.3 # or the latest version
  # Optional, add if you need date formatting
  intl: ^0.18.0
  

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  mockito: ^5.4.1 # For mocking data
  # Add build_runner for code generation
  build_runner: ^2.3.3
