// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnxWmfVk8IubuC-gvBNfuk-mY1EQXUlTM',
    appId: '1:512318365826:web:a109f12ead19500e46d49b',
    messagingSenderId: '512318365826',
    projectId: 'uppgift5-6429d',
    authDomain: 'uppgift5-6429d.firebaseapp.com',
    storageBucket: 'uppgift5-6429d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIF_JUJMSk107oeO8vi-KuzsgdsLHX6gs',
    appId: '1:512318365826:android:e12363ca3ee5d3a046d49b',
    messagingSenderId: '512318365826',
    projectId: 'uppgift5-6429d',
    storageBucket: 'uppgift5-6429d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoF2kYmWsEyLHt6gRdMJkpAwnVD2tPDjo',
    appId: '1:512318365826:ios:cdd5757f89f7096746d49b',
    messagingSenderId: '512318365826',
    projectId: 'uppgift5-6429d',
    storageBucket: 'uppgift5-6429d.firebasestorage.app',
    iosBundleId: 'com.example.adminApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoF2kYmWsEyLHt6gRdMJkpAwnVD2tPDjo',
    appId: '1:512318365826:ios:cdd5757f89f7096746d49b',
    messagingSenderId: '512318365826',
    projectId: 'uppgift5-6429d',
    storageBucket: 'uppgift5-6429d.firebasestorage.app',
    iosBundleId: 'com.example.adminApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnxWmfVk8IubuC-gvBNfuk-mY1EQXUlTM',
    appId: '1:512318365826:web:fe21012e0520221046d49b',
    messagingSenderId: '512318365826',
    projectId: 'uppgift5-6429d',
    authDomain: 'uppgift5-6429d.firebaseapp.com',
    storageBucket: 'uppgift5-6429d.firebasestorage.app',
  );
}
