 
name: shared
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  objectbox: ^4.0.3
  flutter:
    sdk: flutter
  provider: ^6.1.2
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  
  bloc_test: ^9.1.7
  equatable: ^2.0.7
  hydrated_bloc: ^9.1.5
  path_provider: ^2.1.5
  replay_bloc: ^0.2.7
  
   
    
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.13
  lints: ^4.0.0
  objectbox_generator: any
  test: ^1.24.0
