name: cli_server
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0

dependencies:
  args: ^2.4.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  http: ^1.1.0 # Moved from dev_dependencies to dependencies as http is required at runtime

dev_dependencies:
  lints: ^2.0.0 # Updated to match the correct version
  test: ^1.24.0
