name: shared
description: Shared logic and components for the app.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  objectbox: ^4.0.3
  provider: ^6.1.2
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  bloc_test: ^9.1.7
  equatable: ^2.0.7
  hydrated_bloc: ^9.1.5
  path_provider: ^2.1.5
  replay_bloc: ^0.2.7
  firebase_repositories:
    path: ../firebase_repositories
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  lints: ^4.0.0
  mocktail: ^1.0.4
  objectbox_generator: any
  test: ^1.24.0
