name: firebase_repositories
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <4.0.0" # Ensures null safety and Dart 3.x compatibility
  flutter: ">=2.0.0"    # Updated minimum Flutter version for compatibility

dependencies:
  firebase_auth: ^5.4.0      # Ensures compatibility with Firebase Auth
  firebase_core: ^3.10.0     # Compatible version of Firebase Core
  cloud_firestore: ^5.6.1    # Compatible version of Cloud Firestore
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  shared: 
    path: ../shared          # Relative path to the shared module
  uuid: ^4.5.1               # Generates unique IDs

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0      # Linter for best practices
